disabled_rules:
  - todo
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - force_unwrapping
  
type_name:
    max_lenght: 2

line_length:
  warning: 50
  error: 100

excluded:
  - Pods
  - Carthage
  - build
